konstellation-io/kre

admin/admin-api/.gitlab-ci.yml, admin/admin-ui/.gitlab-ci.yml, admin/admin-ui/Dockerfile, admin/k8s-manager/.gitlab-ci.yml, runtime/k8s-runtime-operator/.gitlab-ci.yml, runtime/k8s-runtime-operator/Dockerfile, runtime/mongo-writer/.gitlab-ci.yml, runtime/runtime-api/.gitlab-ci.yml, scripts/krectl/cmd_build.sh
In order to build the KRE Docker images with support of AMD64 and ARM64 we need to build for both architectures. The easiest way looks like is using docker buildx.
=> build multi arch docker image

runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/chronograf/deployment.yml, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/chronograf/pvc.yml, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/minio/statefulset.yaml
These changes will update the Runtime Operator adding the runtime name to the PVC name, solving the issue of local deployment on Minikube with hostPath provisioner where create the same path for those volumes within the host.
Close #245
=> fix: volume claims  names per runtime

admin/admin-ui/src/Pages/Version/pages/Status/components/Tooltip/EntrypointTooltipContent.module.scss, admin/admin-ui/src/Pages/Version/pages/Status/components/Tooltip/EntrypointTooltipContent.tsx, admin/admin-ui/src/Pages/Version/pages/Status/components/Tooltip/Tooltip.module.scss
Short URL:
Medium URL:
Large URL:
=> fix(admin-ui): entrypoint url tooltip now grows with entrypoint length

admin/admin-api/adapter/gql/generated.go, admin/admin-api/adapter/gql/models.go, admin/admin-api/adapter/gql/resolver.go, admin/admin-api/adapter/repository/mongodb/runtime.go, admin/admin-api/adapter/service/runtime.go, admin/admin-api/domain/entity/runtime.go, admin/admin-api/domain/usecase/runtime.go, admin/admin-api/domain/usecase/runtime_test.go, admin/admin-api/schema.graphql, admin/admin-ui/package.json, admin/admin-ui/src/Graphql/types/globalTypes.ts, admin/admin-ui/src/Pages/AddRuntime/AddRuntime.tsx, admin/admin-ui/yarn.lock
- The runtime ID is configurable in the creation process
- Remove all restrictions from the name property (lowercase, minlength=20, etc...)
- Validate Runtime fields on the server side
- Check if the Runtime already exists before creating
=> feat: set the runtime id on creation

admin/k8s-manager/prometheus/resourcemetrics/manager.go, admin/k8s-manager/service/resourcemetrics.go
To solve this issue we have changed the "pod_name", "container_name" to "pod", "container" field names in the prometheus query. For more info:
https://github.com/kubernetes/kubernetes/issues/66790
=> fix: resource metrics not working

libs/simplelogger/simplelogger.go, libs/simplelogger/simplelogger_test.go
this PR is compatible with the current version, but adds an interface and the possibility to write to different output than `os.Stdout`.
=> add SimpleloggerInterface and NewWithWriter() to print output other than os.Stdout.

tests/acceptance/features/Runtime_Version_Management.feature, tests/acceptance/graphql/auth.go, tests/acceptance/graphql/graphql.go, tests/acceptance/graphql/mutation_version_publishing.go, tests/acceptance/graphql/query_version.go, tests/acceptance/main_test.go, tests/acceptance/runner.go, tests/acceptance/version_feature.go
fix url composition on acceptance tests. This way avoids errors with double bar or no bar, and other common errors in url composition
=> fix acceptance tests, substituting versionId with versionName

runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/entrypoint/grpc-ingress.yaml
This will fix the following issue:
> An error has been detected when we try to send a message greater than 2MB. I can reproduce the error with a specific ticket, please contact me to reproduce the error.
**GRPC ERROR**
```
details: 'Received http2 header with status: 413'
debug_error_string: {"created":"@1614705037.147075483","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":129,"grpc_message":"Received http2 header with status: 413","grpc_status":2,"value":"413"}
```
**KST  LOG  => Workflow: entrypoint Process: entrypoint**
```
Exception on gRPC call : Traceback (most recent call last):  File "/app/src/kre_grpc.py", line 37, in process_message    raw_msg = await stream.recv_message()  File …
```
=> fix: increased to 16mb the max body size allowed by the entrypoint ingress

engine/admin-api/adapter/gql/resolver.go
- With the mono-namespace change the entrypoint URL becomes to "entrypoint.<base_domain_name>" instead of "entrypoint.<namespace>.<base_domain_name>"
=> fix: the url for the entrypoint shown in UI is not correct

engine/admin-ui/src/Components/Tag/Tag.module.scss, engine/admin-ui/src/Pages/Version/components/VersionSideBar/RuntimeMenu/RuntimeMenu.module.scss, engine/admin-ui/src/Pages/Version/pages/Status/components/Tooltip/Tooltip.module.scss, engine/admin-ui/src/Styles/app.global.scss
Avoid a SASS warning for making calculations outside the calc function. Although this was valid while using node-sass, updating the dependency deprecated it.
=> fix sass calcs warnings

README.md
There is a missing part in the documentation regarding the repository containing the `kre-runners`. To be able to run the `kre` in a local environment using the `.krectl.sh` cli, you need to clone the `kre-runners` repository to a `runners` folder inside this repository.
=> doc: add kre-runners repo clone step

engine/admin-api/adapter/auth/casbin_access_control.go, engine/admin-api/casbin_rbac_policy.csv, engine/admin-api/domain/usecase/auth_test.go, engine/admin-api/main.go, engine/admin-ui/cypress/integration/versionNavigation.spec.ts, engine/admin-ui/src/Mocks/GetVersionWorkflowsQuery.ts, engine/admin-ui/src/Pages/Version/pages/Status/components/Workflow/WorkflowHeader.tsx, engine/admin-ui/src/Pages/Version/pages/Status/components/Workflow/__snapshots__/Workflow.spec.tsx.snap, engine/admin-ui/src/Pages/Version/pages/Status/components/WorkflowsManager/__snapshots__/WorkflowsManager.spec.tsx.snap, engine/admin-ui/src/rbac-rules.ts
Modify RBAC policy on API to grant view logs permissions to users with viewer role.
Fix the UI to allow viewer users to open the logs console.
=> fix(api): Grant view logs permissions to VIEWER users.

helm/kre/templates/mongo/statefulset.yaml, helm/kre/values.yaml
* Add _nodeSelector_, _taint_ and _affinity options_ to **mongodb** pods
* Add default values for _nodeSelector_, _taint_ and _affinity_ options in `values.yaml` for **InfluxDb** bsubchart
=> Add nodeSelector, taint and affinity options to influxdb and mongodb pods

engine/admin-ui/src/Pages/Version/pages/Status/Status.tsx
When navigating to the status page of a project after navigating to predictions o configuration, the component render fails because the management of a GraphQL subscriptions has a circular dependency. In the first load of status it works because the subscribe function its declared properly, but if its reloaded, this functions isnt declared when the onComplete of the GraphQL useQuery is executed.
To avoid this behavior, the management of the subscription has been move to a useEffect hook, that also manage the unsubscribe, preventing errors related to a high number of subscriptions.
=> fix(ui): navigation to status page after navigating to another page

README.md
Fix a typo in the README in a helm command (line 139).
The rest of the changes in the commit are re-formatting the README to adhere to standards.
=> fix(readme): typo in helm command

engine/admin-ui/package.json, engine/admin-ui/yarn.lock
The build of the Docker UI image takes too long (38 minutes at its last execution). This is due to the download of the material-ui dependencies. Checking why this was not happening in KDL, I noticed that the material-ui dependencies are not in the package.json even though they are being used (I guess because they are being installed together with kwc). I have replicated that behavior in this repository.
=> fix(ui): delete material-ui deps from package.json

helm/kre/templates/engine/admin-api/ingress.yaml, helm/kre/templates/engine/admin-api/issuer.yaml, helm/kre/templates/engine/admin-ui/ingress.yaml, helm/kre/templates/engine/admin-ui/issuer.yaml, helm/kre/templates/engine/entrypoint/grpc-ingress.yaml, helm/kre/templates/engine/entrypoint/nginx-ingress.yaml
Now default ingress anotations depend on `.Values.<component>.tls.enabled` and `.Values.certManager.enabled`
Closes #557
=> fix(helm): Ingresses tls default annotations generation

engine/admin-ui/src/Pages/Version/pages/Status/Status.tsx
On the useEffect that handles the Graphql subscriptions there wasn't any check to avoid multiple subscriptions, causing an overload connections and logs. Also, the status of the nodes didnt update when stopping the version.
=> fix(ui): manage if status component is subscribed before subscribe again

helm/kre/templates/engine/admin-api/ingress.yaml, helm/kre/templates/engine/admin-ui/ingress.yaml, helm/kre/templates/engine/entrypoint/grpc-ingress.yaml, helm/kre/templates/engine/entrypoint/nginx-ingress.yaml
Removed Openshift routes as they are being unmantained.
**IMPORTANT**: This PR introduces a breaking change as Openshift routes are no longer part of the Helm chart.
Closes #570
=> refactor: Remove all Openshift routes from ingress templates

helm/kre/templates/engine/entrypoint/nginx-ingress.yaml
This fixes helm template chomps for `helm/kre/templates/engine/entrypoint/nginx-ingress.yaml` file
=> Fix: Template chomps

engine/admin-ui/src/Graphql/client/typeDefs.ts, engine/admin-ui/src/Graphql/hooks/useLogs.ts, engine/admin-ui/src/Pages/Version/pages/Status/LogsPanel/components/LogsList/LogsList.tsx
Logs filters fails on UI because one field of the request should be deleted.
Delete the runtimesIds field on logs filters.
=> fix(ui): delete runtimesIDs from logs filters on ui

engine/admin-api/adapter/config/config.go, engine/admin-api/domain/usecase/runtime_interactor.go, engine/admin-api/domain/usecase/runtime_interactor_test.go, engine/admin-api/main.go, helm/kre/CHART.md, helm/kre/templates/config/configmap.yaml, helm/kre/values.yaml
Since the new multiruntimes approach allows users to create runtimes, a default runtime isn't needed anymore.
Delete default runtime creation when the api is started.
=> fix(api): delete default runtime creation functionality

scripts/krectl/cmd_delete.sh
For development purpose, multiple versions and runtimes are created, so a script to remove them helps to keep the enviroment clean.
Adapt the old script to delete versions to the multiruntime approach and add the remove runtimes functionality.
=> fix: delete runtime and version script

engine/k8s-manager/config/config.go, engine/k8s-manager/kubernetes/version/containers.go, helm/kre/CHART.md, helm/kre/templates/config/configmap.yaml, helm/kre/values.yaml
`krt-files-downloader` deployment have pull policy "PullIfNotPresent", so, when the tag is latest (as it should be in integrated), the new versions of this component aren't pulled.
Make the image, the tag and the pull policy configurable via Helm in the `k8s-manager` configuration.
=> fix(k8s-manager): add krt-files-downloader images, tag and pull policy configurable via Helm

engine/k8s-manager/kubernetes/version/ingress.go, engine/k8s-manager/kubernetes/version/manager.go
When a version is unpublished, the ingress created when it was published is useless, so deleting it keeps the environment cleaner.
Add function to remove ingress on k8s-manager.
=> fix(k8s-manager): delete created ingress on unpublish version

helm/kre/templates/engine/mongo-writer/deployment.yaml
mongo-writer throws an error when trying to connect to NATS.
Load ConfigMap with the correct NATS URL.
=> fix(mongo-writer): load configmap with NATS URL

engine/admin-api/adapter/repository/influx/measurement.go
When user creates a runtime with hyphens in its ID, InfluxDB throws an error because the request to create a new database doesn't format the name correctly.
Surround the database name in colons to avoid errors on the request.
=> fix(admin-api): format runtime's influx db name to avoid issues with hyphens

engine/admin-api/adapter/config/config.go, engine/admin-api/adapter/service/chronograf.go, engine/admin-api/config.yml, engine/admin-api/delivery/http/middleware/chronograf_proxy.go, engine/admin-api/delivery/http/middleware/mongoexpress_proxy.go, engine/admin-api/delivery/http/middleware/reverse_proxy.go, engine/admin-api/delivery/http/server.go, helm/kre/templates/engine/admin-api/configmap.yaml
This PR introduces the following changes:
* Fix chronograf reverse proxy as it was using a hardcoded hostname for the proxied server
* Refactor of `NewReverseProxyWithDynamicURLTarget` go function that was not adapted to multi-runtime as it is defined now.
=> fix(admin-api): reverse proxy for mongo-express and chronograf

.github/workflows/build_release.yaml, .github/workflows/engine-nats-manager_tests.yaml
I want to build and release nats-manager images on CI/CD pipeline.
Create GitHub Actions for testing and release nats-manager.
=> ci: add nats-manager's test and release actions

engine/nats-manager/service/nats.go, engine/nats-manager/sonar-project.properties
Log indicated that Stop service is beeing executed instead of GetVersionNatsConfig service. Also, I want to force a new image release on nats-manager.
Change the log message.
=> fix(nats-manager): replace log message on GetVersionNatsConfig service

engine/admin-ui/src/Pages/Version/pages/Status/Status.tsx, engine/admin-ui/src/Pages/Version/pages/Status/components/BranchedWorkflowChart/BranchedWorkflowChart.tsx
UI couldn't draw v1 graphs properly because no exitpoint was defined and the first node hadn't the entrypoint in his subscriptions list.
Add exitpoint default node name to workflow configuration and entrypoint to first node subscriptions during v1 to v2 translations on UI.
=> fix(admin-ui): add exitpoint field to v1 workflows and entrypoint to first node subs

.github/workflows/build_release.yaml
Remove the use of `set-output` command in favor of `GITHUB_OUTPUT` environment file.
=> ci(admin-ui): update deprecated gh workflow syntax

scripts/make-kre-user-admin.sh
Added a script to make a user `ADMIN` on the KRE `mongodb` database
The script uses `kubectl` to get the `mongodb` admin password and executes the `mongo` cli on a container to update the user with the `email` address passed as argument if it exists, printing the updated data if succeeds.
I was going to do the change manually and thought that with this command I don't need to remember it anymore.
The command executes the code on a container to simplify things (no need to use port forwarding nor installing the `mongo` cli locally).
I haven't updated the documentation yet, if the addition is OK I guess it has to be documented somewhere (i.e. probably this [section](https://github.com/konstellation-io/konstellation-infrastructure/blob/main/README.md#important-steps-after-redeploying-the-demo- …
=> feat(scripts): add make-kre-user-admin.sh script
