README.md, helm/kre/Chart.yaml, helm/kre/requirements.lock, helm/kre/requirements.yaml, helm/kre/values.yaml.tpl
=> fix(helm): Add prometheus helm chart

k8s-manager/go.sum, k8s-manager/kubernetes/runtime/operator.go
feat(k8s-manager): set replicas to 1 on developmentMode
=> set replicas to 1 on developmentMode

krt-template/go-greeter/src/greeter/main.go, krt-template/greeter/src/greeter/main.py, runners/kre-go/context.go, runners/kre-go/context_data.go, runners/kre-go/context_metrics.go, runners/kre-go/context_test.go, runners/kre-go/runner_test.go, runners/kre-py/README.md, runners/kre-py/src/kre_context.py, runners/kre-py/test/env_vars.sh.tpl, runners/kre-py/test/myvol/src/node/node_handler.py, runners/kre-py/test/test_runner.py
=> refactor for better scope of context methods.

admin/admin-api/adapter/gql/generated.go, admin/admin-api/domain/entity/version.go, admin/admin-api/schema.graphql, admin/admin-ui/src/Graphql/types/globalTypes.ts, admin/admin-ui/src/Pages/Version/pages/Status/components/Workflow/Workflow.module.scss, admin/admin-ui/src/Pages/Version/pages/Status/components/Workflow/WorkflowViz.module.scss, admin/admin-ui/src/Pages/Version/pages/Status/states.ts, admin/admin-ui/src/Styles/_colors.scss, admin/admin-ui/src/Styles/_variables.scss, runtime/runtime-api/entity/node_status.go, runtime/runtime-api/kubernetes/watcher.go, runtime/runtime-api/service/monitoring.go
=> feat: Show error status in workflow processes

scripts/krectl/cmd_build.sh
=> fix: remove dependency on yarn moving admin-ui build inside a container.

admin/admin-api/.gitlab-ci.yml, admin/admin-api/Dockerfile, admin/admin-api/go.mod, admin/k8s-manager/.golangci.yml, admin/k8s-manager/Dockerfile, admin/k8s-manager/go.mod, admin/k8s-manager/kubernetes/version/config.go, admin/k8s-manager/kubernetes/version/entrypoint.go, admin/k8s-manager/kubernetes/version/node.go, admin/k8s-manager/kubernetes/watcher.go, admin/k8s-manager/service/resourcemetrics.go, admin/k8s-manager/service/runtime.go, admin/k8s-manager/service/version.go, helm/kre/values.yaml.tpl, runtime/mongo-writer/Dockerfile, runtime/mongo-writer/go.mod, runtime/runtime-api/.gitlab-ci.yml, runtime/runtime-api/Dockerfile, runtime/runtime-api/go.mod
=> feat: update all images to go version 1.14 and enable lint on k8s-manager

admin/admin-ui/package.json, admin/admin-ui/src/Graphql/client/resolvers/version.ts, admin/admin-ui/src/Graphql/client/typeDefs.ts, admin/admin-ui/src/Graphql/queries/getVersionWorkflows.graphql, admin/admin-ui/src/Graphql/queries/types/GetVersionWorkflows.ts, admin/admin-ui/src/Pages/Version/components/VersionSideBar/VersionMenu/VersionMenuItem.tsx, admin/admin-ui/src/Pages/Version/pages/Status/Status.tsx, admin/admin-ui/src/Pages/Version/pages/Status/components/ResourceMetrics/ResourceMetrics.tsx, admin/admin-ui/src/Pages/Version/pages/Status/components/Tooltip/Tooltip.module.scss, admin/admin-ui/src/Pages/Version/pages/Status/components/Workflow/Workflow.tsx, admin/admin-ui/src/Pages/Version/pages/Status/components/Workflow/WorkflowChart.tsx, admin/admin-ui/src/Pages/Version/pages/Status/components/Workflow/WorkflowViz.module.scss, admin/admin-ui/src/Pages/Version/pages/Status/components/Workflow/WorkflowViz.tsx, admin/admin-ui/src/Pages/Version/pages/Status/components/WorkflowsManager/WorkflowsManager.tsx, admin/admin-ui/src/Pages/Version/pages/Status/states.ts, admin/admin-ui/src/Styles/_variables.scss, admin/admin-ui/src/extensions.graphql, admin/admin-ui/src/index.tsx, admin/k8s-manager/kubernetes/version/entrypoint.go, runtime/runtime-api/kubernetes/watcher.go
=> feat: Show entrypoint status

admin/admin-api/delivery/http/controller/auth.go
=> fix(admin-api): An expired auth code in login creates an invalid JWT token

helm/kre/Chart.lock, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/mongo/statefulset.yaml
=> fix(runtime): mongo pvc name

admin/admin-api/adapter/gql/generated.go, admin/admin-api/adapter/gql/resolver.go, admin/admin-api/schema.graphql, admin/admin-ui/src/Components/NotificationService/Services/onRuntimeCreated/onRuntimeCreated.tsx, admin/admin-ui/src/Graphql/subscriptions/types/GetLogs.ts, admin/admin-ui/src/Graphql/subscriptions/types/runtimeCreated.ts, admin/admin-ui/src/Graphql/subscriptions/watchNodeLogs.graphql, admin/admin-ui/src/Graphql/subscriptions/watchRuntimeCreated.graphql, admin/admin-ui/src/Mocks/runtime.ts, admin/admin-ui/src/Pages/Version/pages/Status/LogsPanel/components/LogsList/LogsList.tsx
=> feat: add watch prefix to graphql subscriptions

admin/k8s-manager/prometheus/resourcemetrics/manager.go
=> fix: add empty metric when version stop

README.md, admin/admin-api/adapter/gql/resolver.go, admin/admin-api/adapter/repository/minio/minio.go, admin/admin-api/adapter/repository/mongodb/version.go, admin/admin-api/domain/entity/version.go, admin/admin-api/domain/usecase/krt/parser.go, admin/admin-api/domain/usecase/version_interactor.go, admin/admin-api/schema.graphql, admin/admin-ui/mock-server/src/mock.js, admin/admin-ui/src/Components/NotificationService/NotificationService.tsx, admin/admin-ui/src/Components/NotificationService/Services/onVersionCreated/onVersionCreated.tsx, admin/admin-ui/src/Graphql/types/globalTypes.ts, admin/admin-ui/src/Pages/AddVersion/AddVersion.tsx, admin/admin-ui/src/Pages/Version/components/VersionSideBar/VersionActions/VersionActions.tsx, admin/admin-ui/src/Styles/_funcs.scss, admin/admin-ui/src/Styles/_variables.scss
=> feat: add async version upload

admin/k8s-manager/config.yml, admin/k8s-manager/config/config.go, admin/k8s-manager/kubernetes/version/entrypoint.go, helm/kre/templates/config/configmap.yaml, runners/kre-entrypoint/entrypoint-gen/entrypoint.py.tmpl, runners/kre-entrypoint/entrypoint-gen/generate_entrypoint_test.go, runners/kre-entrypoint/entrypoint.sh, runners/kre-entrypoint/src/kre_grpc.py, runners/kre-entrypoint/src/main.py
=> add request_timeout as environment variable for kre-py

.krectl.conf, admin/admin-ui/public/config/config.json.tpl, helm/kre/templates/admin-ui/admin-ui-configmap.yaml, helm/kre/templates/config/configmap.yaml, helm/kre/values.yaml.tpl, scripts/krectl/cmd_dev.sh
=> fix: add environment variable KRE_ADMIN_API_BASE_URL to admin-api config.

helm/kre/templates/admin-api/deployment.yaml, helm/kre/templates/admin-api/ingress.yaml, helm/kre/templates/admin-api/service.yaml, helm/kre/templates/admin-ui/deployment.yaml, helm/kre/templates/admin-ui/ingress.yaml, helm/kre/templates/admin-ui/service.yaml, helm/kre/templates/config/configmap.yaml, helm/kre/templates/k8s-manager/deployment.yaml, helm/kre/templates/k8s-manager/service.yaml, helm/kre/values.yaml.tpl, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/runtime-api/deployment.yaml, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/runtime-api/service.yaml
For better usability fix ports that doesn't need to be open on `values.yaml` 
Closes #280
=> fix: remove ports from values.yaml 

runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/entrypoint/grpc-ingress.yaml, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/entrypoint/nginx-ingress.yaml, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/runtime-default-backend/config.yml, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/runtime-default-backend/deployment.yaml, runtime/k8s-runtime-operator/helm-charts/kre-chart/templates/runtime-default-backend/service.yaml
=> feat: add default pages and grpc responses for when no entrypoint is active

scripts/krectl/cmd_deploy.sh
During the execution of the `./krectl.sh` script with the `dev --skip-build` options an error occurs in the `scripts/krectl/cmd_deploy.sh` script when the client version of `kubectl` is less than 1.18.0.
This error is due to the fact that in versions of kubectl prior to 1.18.0 for the creation of objects the option `--dry-run=client` did not exist, therefore a function is created that checks the version of kubectl to use --dry-run with the option `=client` or not as appropriate.
=> fix: Add kubectl version check to use --dry-run with or without client option

admin/admin-ui/src/Pages/Version/components/VersionSideBar/BackButton/BackButton.module.scss, admin/admin-ui/src/Pages/Version/components/VersionSideBar/BackButton/BackButton.tsx, admin/admin-ui/src/Pages/Version/components/VersionSideBar/RuntimeMenu/RuntimeMenu.module.scss, admin/admin-ui/src/Pages/Version/components/VersionSideBar/RuntimeMenu/RuntimeMenu.tsx, admin/admin-ui/src/Pages/Version/components/VersionSideBar/VersionMenu/VersionMenu.tsx, admin/admin-ui/src/Pages/Version/components/VersionSideBar/VersionSideBar.module.scss, admin/admin-ui/src/Pages/Version/components/VersionSideBar/VersionSideBar.tsx
=> feat(admin-ui): move runtime links below back button on version sidebar

runners/kre-entrypoint/entrypoint-gen/entrypoint.py.tmpl, runners/kre-entrypoint/entrypoint-gen/go.mod, runners/kre-entrypoint/src/kre_grpc.py
=> fix: Add error on GRPC entrypoints

admin/admin-api/adapter/gql/resolver.go
used for notifications to avoids service restart on concurrent access to it. Closes #343
=> fix: add mutex for read/write to map of channels

krt-template/greeter/src/greeter/main.py, runners/kre-py/src/context_prediction.py
=> fix: only fail to convert when date utcoffset() exists and is not zero.

runners/kre-py/src/context_prediction.py
We have found a case in which the data scientist would save more useful information to carry out monitoring when making predictions.
By adding this field, I think we could solve future needs for ours and other projects.
=> Add extra field to save predictions function

.github/workflows/build_release.yaml, helm/kre-monoruntime/Chart.lock, helm/kre-monoruntime/Chart.yaml
=> publish monoruntime chart. fix Chart.yaml version

.github/workflows/pre-release.yaml, .github/workflows/release.yaml, README.md, libs/krt-utils/README.md
Change references from master branch to main branch in workflows and README files
=> build(branch): change references from master to main

.github/workflows/README.md
Add a README explaining the workflows
=> docs(workflows): document workflows

helm/kre/Chart.lock, helm/kre/Chart.yaml, helm/kre/templates/_helpers.tpl, helm/kre/templates/engine/chronograf/config.yml, helm/kre/templates/engine/chronograf/deployment.yml, helm/kre/values.yaml, scripts/krectl/cmd_deploy.sh
* Add Kapacitor Helm chart 1.4.0 as dependency
* Add **kre_kapacitor.kap** file to `chronograf-config` configmap
* Update `values.yml`
* Update `scripts/krectl/cmd_deploy.sh`
=> Feature: Add Kapacitor dependency

README.md, krt-template/scripts/build_krt.sh
Update `krectl.sh` script to make it work with `yq` latest version.
=> fix: update yq to v4

.github/workflows/build_release.yaml, engine/admin-ui/.dockerignore, engine/admin-ui/Dockerfile, engine/admin-ui/Dockerfile.builder, engine/admin-ui/Dockerfile.builder.dockerignore, engine/admin-ui/package.json, engine/admin-ui/yarn.lock, scripts/krectl/cmd_build.sh
Delete unused yarn build on GitHub Workflow, delete Dockerfile.builder, and integrate build step into a single Dockerfile.
=> fix: ui image build

engine/admin-ui/.yarnrc
Increase timeout during yarn packages download
=> fix(ui): increase yarn timeout

helm/kre/templates/config/clusterissuer.yaml, helm/kre/templates/engine/admin-api/ingress.yaml, helm/kre/templates/engine/admin-api/issuer.yaml, helm/kre/templates/engine/admin-ui/ingress.yaml, helm/kre/templates/engine/admin-ui/issuer.yaml, helm/kre/templates/engine/entrypoint/grpc-ingress.yaml, helm/kre/templates/engine/entrypoint/nginx-ingress.yaml, helm/kre/values.yaml
Please review it. With this PR I will update the following things:
- Provide custom annotations in all ingress resources.
- Provide custom configuration for cert-manager.
- Update the apiversion for cert-manager clusterissuer and issuer resource.
=> fix: Custom annotations values on ingress and configure cert-manager

engine/k8s-manager/Dockerfile
=> fix: Force new prerelease

engine/k8s-manager/kubernetes/version/manager_node.go
Add a feature to configure a workflow node with nodeSelector and Tolerations based on GPU requirements.
If a node in the `krt.yml` has the property `gpu: true` then:
- Add to the node deployment a NodeSelector: `"konstellation.io/gpu" = true`
- Add to the node deployment two new Tolerations: 
```
{
Key:      "konstellation.io/gpu",
Operator: apiv1.TolerationOpExists,
Effect:   apiv1.TaintEffectNoSchedule,
},
{
Key:      "nvidia.com/gpu",
Operator: apiv1.TolerationOpExists,
Effect:   apiv1.TaintEffectNoSchedule,
},
```
=> feat(workflows): nodeSelector and toleration for gpu nodes

engine/admin-api/adapter/config/config.go, engine/admin-api/domain/usecase/logging/interface.go, engine/admin-api/domain/usecase/logging/logger.go, engine/admin-api/main.go, helm/kre/templates/engine/admin-api/deployment.yaml, helm/kre/values.yaml
Log level was set to DEBUG and it couldn't be configured. This change makes the log level configurable.
=> fix(api): add configurable log level

engine/k8s-manager/kubernetes/version/entrypoint.go, engine/k8s-manager/kubernetes/version/manager.go
With this feature all versions in `STARTED` status will have a `Service` attached, so users can reach the entrypoint from inside the cluster. The `serviceName` for the `Service` is the release version name.
A published version will replace the service for a service with a `serviceName` equal to `active-entrypoint`.
Example for a `STARTED` version entrypoint's `Service`:
```
apiVersion: v1
kind: Service
metadata:
creationTimestamp: "2022-03-28T13:23:40Z"
labels:
type: entrypoint
version-name: greeter-v7
name: greeter-v7-entrypoint
namespace: kre
resourceVersion: "11275" 
selfLink: /api/v1/namespaces/kre/services/greeter-v7-entrypoint
uid: 747e7d01-2278-4ee7-8fc7-d158293c1697 
spec:
clusterIP: 10.108.63.40
ports:
- name: grpc
port: 9000
protocol: TCP
targetPort: 9000
- name: web
port: 80 …
```
=> feat: services for entrypoints

krt-template/greeter/krt.yml, krt-template/greeter/metrics/dashboards/application.json
We noticed some errors during our go-greeter tests. Upon further research we noticed the greeters example need the latest images of the runners to be deployed alongside local builds.
Also, some displays in the generated dashboards were not working correctly.
- Updated runners version to latest
- Fixed dashboards
=> fix(greeter): upgrade runner versions and fix dashboards

helm/kre/README.md
This adds major changes for release 3.0 to `helm/kre/README.md`
=> doc: add rbac changes to chart's README.md

.github/workflows/pre-release.yaml, engine/k8s-manager/go.mod, engine/k8s-manager/go.sum
Multiruntime feature needs to upgrade the major version of the product
Upgrade major from 3 to 4 in the pre-release action
=> new major version 4 in pre-release action

README.md
This PR update de docs related with the local dev environment.
=> doc: update krectl docs

.github/workflows/build_release.yaml, .github/workflows/engine-admin-api_tests.yaml, .github/workflows/engine-admin-ui_test.yaml, .github/workflows/engine-k8s-manager_tests.yaml, .github/workflows/engine-mongo-writer_tests.yaml, .github/workflows/fix.yaml, .github/workflows/pre-release.yaml, .github/workflows/release.yaml
Update Github actions used to avoid deprecated warnings.
=> fix(workflow): update github actions

helm/kre/CHART.md, helm/kre/templates/engine/chronograf/deployment.yml, helm/kre/values.yaml
**WHY**
As a chart user I want to set the chronograf image repository, tag and pullPolicy.
**WHAT**
* Added `chronograf.image.repository`, `chronograf.image.tag` and `chronograf.image.pullPolicy` to `values.yaml` file.
=> feat(helm): add `chronograf.image` values to `values.yaml` file

.github/workflows/build_release.yaml
Avoid error of chart releaser.
=> fix: Add influx helm registry

engine/admin-ui/README.md, engine/admin-ui/mock-server/src/mock.js, engine/admin-ui/src/Graphql/queries/getVersionWorkflows.ts, engine/admin-ui/src/Graphql/queries/types/GetVersionWorkflows.ts, engine/admin-ui/src/Mocks/version.ts, engine/admin-ui/src/Pages/Version/pages/Status/Status.tsx, engine/admin-ui/src/Pages/Version/pages/Status/components/Workflow/Workflow.spec.tsx
BREAKING CHANGE: From now on krt-v1 versions will not be supported in KRE. 
This commit also refactors code and some internal logic.
With these changes we would like to encourage teams using Konstellation to upgrade their code bases to krt-v2.
=> refactor(admin-ui): Deprecate krt-v1 support

README.md
Configure SonarCloud to analyze the Kai Lab.
We need to have more visibility on the status of the project and the quality of the new code.
This is why we need to configure the SonarCloud analysis.
I've also renamed the workflow files to match a common pattern and to be more structured
=> Sonarcloud integration

scripts/krectl/cmd_build.sh
Remove exitpoint build stage during kre deployment.
Kre-exitpoint has been deprecated as we no longer support krt v1.
=> feat(kre): remove exitpoint build

helm/kre/values.yaml
We need to test file upload to the object store bigger than 1GB. Currently, the NATS client is returning a resource limit error.
=> fix(helm-values): Update storage limits for nats jetstream

.github/workflows/build_release.yaml
The natsManager was missing on the version update script on the helm step.
=> Fix helm build, add natsManager to the version update step

helm/kre/CHART.md, helm/kre/templates/engine/nats/configmap.yaml, helm/kre/values.yaml, scripts/helmfile/helmfile.lock
=> feat: add limits config to NATS (KNT1-309)

engine/k8s-manager/config/config.go, engine/k8s-manager/kubernetes/version/entrypoint.go, engine/k8s-manager/kubernetes/version/manager_node.go, helm/kre/templates/engine/k8s-manager/configmap.yaml
=> Add js timeout env variable
